### ISSUE TITLE
Advertise the existence of this library

### ISSUE THREAD

**Issue by jvican** [sherpal/Scala-Google-Spreadsheets#1]
Hey there @sherpal, nice work here. I stumbled upon this by pure luck, and didn't see the bindings library in the official Scala.js library, I think it would be great if you send a pull request to add it there, as well as rename the library to `scala-google-spreadsheets`, in lowercase, in accordance with existing libraries like https://github.com/coreyauger/scalajs-google-maps.

**Comment by sherpal** [comment]
Hello,

Thanks for your message. Originally this project was intended for my own usage, hence I didn't bother to advertise it much.
I made a pull request for the scala.js website, in order to add this project to the skeleton project examples.
